const fakeVideo = [
  {
    kind: "youtube#video",
    etag: "TJBCirsO95Un2HqNYqZ1ek_fiTo",
    id: {
      videoId: "J0lKgt7dxbU",
    },
    snippet: {
      publishedAt: "2019-07-16T16:54:26Z",
      channelId: "UCK4UNRVpb9_lZVf0zUSkJDw",
      title: 'Quinn XCII - "Stacy" Live Performance | Vevo',
      description:
        'Quinn XCII - Stacy (Live Performance) \n\nWe don\'t have a lot of artists arrive at the Vevo studios with a string trio, but Quinn XCII had two violinists and a cellist in tow when he arrived to drop a poignant spin on his brand new song, "Stacy." Fans know Quinn\'s been turning heads for the last few years; his last two albums, \'The Story of Us\' and \'From Michigan With Love,\' moved him forward on the pop racetrack - these days more and more people are declaring their love for the Detroit native (whose real name is Mikael Temrowski). Massive Spotify streaming numbers for "Straightjacket" and "Flareguns" helped a lot towards this victory. Ditto for videos such "Tough," whose track featured Noah Kahan. See where the strings and piano take him in this stripped-down version of "Stacy." \n\nViolin: Molly Fletcher\nViolin: Chiara Fasi\nCello: Kristine Kruta\nPiano: J.T. Becker \n\nExecutive Producer: Micah Bickham\nDirector: Kyle Goldberg\nProducer: Sacha Noelle\nDirector of Photography: Bram Vandermark\nEditor: Ramy Elsokary\nMusic & Talent: Gabriela Prisciandaro, Sam Mackoff\n\nVevo \nhttp://facebook.com/vevo\nhttp://twitter.com/vevo\nhttp://instagram.com/vevo\n\nQuinn XCII:\nhttp://quinnxcii.com/\nhttps://www.facebook.com/quinnxcii\nhttps://twitter.com/quinnxcii\nhttps://www.instagram.com/quinnxcii \n\nWatch Quinn XCII music videos:  https://bit.ly/2Jzfjh1\nListen to "Stacy" https://youtu.be/wMIXt_9lZAU  \n\n#QuinnXCII  #QuinnXCIILive  #Stacy\n\nhttp://vevo.ly/kK6b34',
      thumbnails: {
        default: {
          url: "https://i.ytimg.com/vi/J0lKgt7dxbU/default.jpg",
          width: 120,
          height: 90,
        },
        medium: {
          url: "https://i.ytimg.com/vi/J0lKgt7dxbU/mqdefault.jpg",
          width: 320,
          height: 180,
        },
        high: {
          url: "https://i.ytimg.com/vi/J0lKgt7dxbU/hqdefault.jpg",
          width: 480,
          height: 360,
        },
        standard: {
          url: "https://i.ytimg.com/vi/J0lKgt7dxbU/sddefault.jpg",
          width: 640,
          height: 480,
        },
        maxres: {
          url: "https://i.ytimg.com/vi/J0lKgt7dxbU/maxresdefault.jpg",
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "QuinnXCIIVEVO",
      tags: [
        "Quinn XCII",
        "Stacy",
        "Live",
        "Performance",
        "Vevo",
        "Columbia",
        "Pop",
        "new Quinn XCII",
        "Quinn XCII live",
        "Quinn XCII performance",
        "Quinn XCII Vevo",
        "Quinn XCII videos",
        "new Quinn XCII video",
        "pop music",
        "pop music videos",
        "streaming music",
        "Quinn XCII Stacy",
        "Stacy video",
        "At the 50 yard line",
        "I saw her feet She was under the bleachers",
        "waiting for me No",
        "I never get high",
        "but",
        "I'm",
        "smoking",
        "her",
        "weed She",
        "been",
        "giving",
        "this",
        "freshman",
        "love",
        "since",
        "last",
        "June The",
      ],
      categoryId: "10",
      liveBroadcastContent: "none",
      localized: {
        title: 'Quinn XCII - "Stacy" Live Performance | Vevo',
        description:
          'Quinn XCII - Stacy (Live Performance) \n\nWe don\'t have a lot of artists arrive at the Vevo studios with a string trio, but Quinn XCII had two violinists and a cellist in tow when he arrived to drop a poignant spin on his brand new song, "Stacy." Fans know Quinn\'s been turning heads for the last few years; his last two albums, \'The Story of Us\' and \'From Michigan With Love,\' moved him forward on the pop racetrack - these days more and more people are declaring their love for the Detroit native (whose real name is Mikael Temrowski). Massive Spotify streaming numbers for "Straightjacket" and "Flareguns" helped a lot towards this victory. Ditto for videos such "Tough," whose track featured Noah Kahan. See where the strings and piano take him in this stripped-down version of "Stacy." \n\nViolin: Molly Fletcher\nViolin: Chiara Fasi\nCello: Kristine Kruta\nPiano: J.T. Becker \n\nExecutive Producer: Micah Bickham\nDirector: Kyle Goldberg\nProducer: Sacha Noelle\nDirector of Photography: Bram Vandermark\nEditor: Ramy Elsokary\nMusic & Talent: Gabriela Prisciandaro, Sam Mackoff\n\nVevo \nhttp://facebook.com/vevo\nhttp://twitter.com/vevo\nhttp://instagram.com/vevo\n\nQuinn XCII:\nhttp://quinnxcii.com/\nhttps://www.facebook.com/quinnxcii\nhttps://twitter.com/quinnxcii\nhttps://www.instagram.com/quinnxcii \n\nWatch Quinn XCII music videos:  https://bit.ly/2Jzfjh1\nListen to "Stacy" https://youtu.be/wMIXt_9lZAU  \n\n#QuinnXCII  #QuinnXCIILive  #Stacy\n\nhttp://vevo.ly/kK6b34',
      },
    },
    statistics: {
      viewCount: "169453",
      likeCount: "4851",
      dislikeCount: "46",
      favoriteCount: "0",
      commentCount: "183",
    },
  },
];
export default fakeVideo;
